services:
  auth-db:
    container_name: auth-db-container
    image: mysql:latest
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASS}
    ports:
      - "${DATABASE_PORT_HOST}:${DATABASE_PORT_CONTAINER}"
    volumes:
      - auth-db-volume:/var/lib/mysql
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    networks:
      - auth-network
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 30s
      timeout: 20s
      retries: 10
    restart: always

  auth-api:
    container_name: auth-api-container
    image: auth-api-image
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    depends_on:
      auth-db:
        condition: service_healthy
    ports:
      - "${API_PORT_HOST}:${API_PORT_CONTAINER}"
    networks:
      - auth-network
    stdin_open: true
    tty: true
    restart: always

volumes:
  auth-db-volume:

networks:
  auth-network:
